apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: app

resources:
- config/app.yaml
- shopware-init.yaml
- app-server.yaml
- ingress.yaml
- message-consumer.yaml
- task-scheduler.yaml
