apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer
  namespace: development
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8080
  selector:
    app: adminer
