apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cypress
  name: cypress
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cypress
  strategy: {}
  template:
    metadata:
      labels:
        app.network/shopware: "true"
        app: cypress
    spec:
      containers:
        - command:
            - /bin/bash
          env:
            - name: CYPRESS_baseUrl
              value: http://docker.vm:8000
            - name: DISPLAY
              value: /private/tmp/com.apple.launchd.xL3Kpp4MUs/org.macosforge.xquartz:0
          image: cypress/included:4.10.0
          name: cypress
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
