apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailhog
  name: mailhog
  namespace: development
spec:
  ports:
    - name: "8025"
      port: 8025
      targetPort: 8025
    - name: "1025"
      port: 1025
      targetPort: 1025
  selector:
    app: mailhog