apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
namespace: development
configMapGenerator:
  - name: env
    envs:
      - .env
  - name: env-file
    files:
      - .env
