apiVersion: v1
kind: Service
metadata:
  name: redis-session
  labels:
    app: redis-session
spec:
  selector:
    app: redis-session
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: metrics
    port: 9121
    protocol: TCP
    targetPort: metrics

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-session
spec:
  selector:
    matchLabels:
      app: redis-session
  serviceName: redis-session
  template:
    metadata:
      labels:
        app: redis-session
    spec:
      containers:
      - name: redis-session
        image: redis:7.2.5
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        ports:
          - name: redis
            containerPort: 6379
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
      - name: prometheus-exporter
        image: oliver006/redis_exporter:v1.62.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
          - name: metrics
            containerPort: 9121
