apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: message-consumer
    k8s-app: shopware
  name: message-consumer
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-consumer
  template:
    metadata:
      labels:
        k8s-app: shopware
        app: message-consumer
    spec:
      containers:
        - name: message-consumer
          image: kiweeteam/shopware-demo-mc:6.4.11.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env
          resources: {}
          volumeMounts:
            - mountPath: /tmp
              name: message-consumer-tmpfs0
            - mountPath: /app/public/media
              name: media
            - mountPath: /app/public/thumbnail
              name: thumbnail
            - mountPath: /app/files
              name: files
            - mountPath: /app/public/sitemap
              name: sitemap
            - mountPath: /app/.env
              subPath: .env
              name: env-file
          readinessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            exec:
              command:
                - ls
                - /app/install.lock
      restartPolicy: Always
      volumes:
        - name: message-consumer-tmpfs0
          emptyDir:
            medium: Memory
            sizeLimit: 200M
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: thumbnail
          persistentVolumeClaim:
            claimName: thumbnail
        - name: files
          persistentVolumeClaim:
            claimName: files
        - name: sitemap
          persistentVolumeClaim:
            claimName: sitemap
        - name: env-file
          configMap:
            name: env-file
