apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-server
    k8s-app: shopware
  name: app-server
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        k8s-app: shopware
        app: app-server
    spec:
      containers:
        - name: app-server
          image: kiweeteam/shopware-demo:6.4.11.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env
          ports:
            - containerPort: 8000
            - containerPort: 8080
            - containerPort: 9998
            - containerPort: 9999
          resources: {}
          volumeMounts:
            - mountPath: /tmp
              name: app-server-tmpfs0
            - mountPath: /app/public/media
              name: media
            - mountPath: /app/public/thumbnail
              name: thumbnail
            - mountPath: /app/files
              name: files
            - mountPath: /app/public/sitemap
              name: sitemap
            - mountPath: /app/.env
              subPath: .env
              name: env-file
          readinessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            exec:
              command:
                - ls
                - /app/install.lock
      restartPolicy: Always
      volumes:
        - name: app-server-tmpfs0
          emptyDir:
            medium: Memory
            sizeLimit: 200M
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: thumbnail
          persistentVolumeClaim:
            claimName: thumbnail
        - name: files
          persistentVolumeClaim:
            claimName: files
        - name: sitemap
          persistentVolumeClaim:
            claimName: sitemap
        - name: env-file
          configMap:
            name: env-file
