apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-server
  name: app-server
  namespace: development
spec:
  type: ClusterIP
  ports:
    - name: http-app
      port: 8000
      targetPort: 8000
    - name: http-admin
      port: 8080
      targetPort: 8080
    - name: http-storefront
      port: 9998
      targetPort: 9998
    - name: http-storefront2
      port: 9999
      targetPort: 9999
  selector:
    app: app-server
