apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: job-scheduler
    k8s-app: shopware
  name: job-scheduler
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-scheduler
  template:
    metadata:
      labels:
        k8s-app: shopware
        app: job-scheduler
    spec:
      containers:
        - name: job-scheduler
          image: kiweeteam/shopware-demo-js:6.4.11.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env
          resources: {}
          volumeMounts:
            - mountPath: /tmp
              name: job-scheduler-tmpfs0
            - mountPath: /app/public/media
              name: media
            - mountPath: /app/public/thumbnail
              name: thumbnail
            - mountPath: /app/files
              name: files
            - mountPath: /app/public/sitemap
              name: sitemap
            - mountPath: /app/.env
              subPath: .env
              name: env-file
      restartPolicy: Always
      volumes:
        - name: job-scheduler-tmpfs0
          emptyDir:
            medium: Memory
            sizeLimit: 200M
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: thumbnail
          persistentVolumeClaim:
            claimName: thumbnail
        - name: files
          persistentVolumeClaim:
            claimName: files
        - name: sitemap
          persistentVolumeClaim:
            claimName: sitemap
        - name: env-file
          configMap:
            name: env-file
