apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: files
  name: files
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
