apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cache
  namespace: development
spec:
  selector:
    matchLabels:
      app: redis-cache
  serviceName: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
        - name: redis
          image: redis:6.2.7-alpine3.16
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 250m
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 1Gi