apiVersion: v1
kind: Service
metadata:
  name: redis-session
  namespace: development
  labels:
    app: redis-session
spec:
  selector:
    app: redis-session
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
