apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  namespace: development
  labels:
    app: redis-cache
spec:
  selector:
    app: redis-cache
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379