apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sitemap
  name: sitemap
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
