---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: database-credentials
spec:
  forceRegenerate: false
  data:
    MYSQL_USER: "shopware"
    MYSQL_DATABASE: "shopware"
    MYSQL_HOST: "db"
    MYSQL_PORT: "3306"
  fields:
    - fieldName: "MYSQL_PASSWORD"
      encoding: "base64url"
      length: "20"
    - fieldName: "MYSQL_ROOT_PASSWORD"
      encoding: "base64url"
      length: "20"
