apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: database

resources:
  - credentials.yaml
  - config/init.yaml
  - database.yaml

configMapGenerator:
  - name: mycnf
    files:
      - config/my.cnf
