apiVersion: v1
kind: ConfigMap
metadata:
  name: testdb-init-sql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS shopware_test;
    GRANT ALL PRIVILEGES ON shopware_test.* TO 'shopware'@'%';
    FLUSH PRIVILEGES;
